### PR TITLE
Add native compile option to use latest vector instructions

### PR DESCRIPTION
**Pull request by cangumeli**

### CODE REVIEW

**Comment by giangiac** [comment]
I am fine with the change. This should be incorporated in Fabio's cmake larger update.

**Comment by cangumeli** [comment]
Ok, I can merge Fabio's changes into this branch, after Fabio's changes are merged.

**Comment by giangiac** [comment]
Hi Can, I am testing the "review" process. I just submit a commit to test the ability of modifying your pull request. Did you see my commit in your forked repo? Branch "native_compilation" is not part of iqusoft/intel-qs repo, correct?

**Comment by fbaru-dev** [comment]
Hi Can,
please resolve the conflicts, so I can merge to the master and accept this pull request.
F.

**Comment by cangumeli** [comment]
> Hi Can, I am testing the "review" process. I just submit a commit to test the ability of modifying your pull request. Did you see my commit in your forked repo? Branch "native_compilation" is not part of iqusoft/intel-qs repo, correct?
Yes, I see it.

**Comment by cangumeli** [comment]
I think it would be cleaner if I re-open this PR.

**Pull request closed without merging**
