### PR TITLE
WIP Develop/cmake

### PR DESCRIPTION
**Pull request by giangiac**
Multiple improves to the cmake process:
* divide CMakeLists.txt into separate files added in src/ unit_test/ examples/  
(currently there is a monolithic CMakeLists.txt in the main directory of the repo)
* lower cmake required version to 3.12
* build IQS both as a static (default target of the project) and shared library

### CODE REVIEW

**Comment by giangiac** [comment]
Fabio, the work is still in progress.
I will soon commit a few changes to solve the current compile issues.

**Comment by giangiac** [comment]
At the moment, only the static library is built.
The shared one can be added by un-commenting a few lines in src/CMakeLists.txt.

Tested with:
CXX=mpiicpc cmake -DIqsPython=ON -DIqsUtest=ON -DIqsMPI=OFF -DBuildExamples=ON ..

TODO: test with MPI

**Comment by fbaru-dev** [comment]
I resolved all the conflicts and updated the build. Now we generate only the shared library and all the dependencies are built independently, so one can easily understand how to link an external additional file to the iqs library.

**Comment by giangiac** [comment]
Delete branch for clean-up.

**Pull request merged**
