### PR TITLE
Create workflow for C++ build with CMake

### PR DESCRIPTION
**Pull request by giangiac**
The workflow is contained in 'cpp_build_with_cmake.yml'.
Basic build in Ubuntu using gcc compiler.

### CODE REVIEW

**Comment by fbaru-dev** [comment]
I checked all the steps and it looks fine for me

**Review by fbaru-dev — APPROVED** [review]
I approve your changes

**Comment by fbaru-dev** [comment]
@giangiac  Should I merge all in one commit or you prefer to have all the 10? I would suggest one commit, but I need your opinion

**Comment by giangiac** [comment]
@fbaru-dev I would say one commit and than the branch should be deleted.

**Comment by fbaru-dev** [comment]
Accepted the merge

**Pull request merged**
